services:
  hyundai-bridge:
    # Hier holen wir jetzt das fertige Image von GitHub!
    image: ghcr.io/bausi2k/hyundai-loxone-bridge:latest
    container_name: hyundai-loxone-bridge
    restart: unless-stopped
    ports:
      - "8444:8444"
    volumes:
      # Speichert die config.json dauerhaft, auch wenn der Container ein Update bekommt
      - ./config.json:/app/config.json
    environment:
      - TZ=Europe/Vienna # Wichtig für die korrekten Zeitstempel